### ISSUE TITLE
pudl0038 Historical Photograph Collection: Grounds and Buildings Series

### ISSUE THREAD

**Issue by cwulfman** [pulibrary/pudl-migration#23]

**Comment by cwulfman** [comment]
On July 2, 2020 Lynn Durgin wrote:
>Hi Cliff, 

Thank you for reaching out. 

Yes; the Figgy resources are ready to be matched up with their component IDs.

In addition, many changes were made to the item metadata, so the fields: title, subject, date, end date, approximate, location, photographer and description should all be uploaded into Figgy to replace what is currently there. Changes were not only made to the items that had notes from Barksdale, so the metadata for all of the items should be replaced. Does that make sense?

We plan to begin working on the Historical Postcard Collection next week. Please let me know if you have any questions or concerns.

Thank you,
Lynn

**Comment by cwulfman** [comment]
- [x] create a MVW for each component ID with multiple digital objects, attaching existing scanned resources as children
- [x] then, add a component ID to each figgy object to trigger remote metadata
- [x] finally, import the remaining metadata from the spreadsheet into Figgy

The last step will require creating a custom rake task

**Comment by cwulfman** [comment]
Ready for stakeholder review.

**Comment by kelea99** [comment]
Recent questions from stakeholders:

Is it possible to display the box (and item number, if possible) in one of the metadata fields in the “More information” area? We have this information in the PUDL, it is present in the spreadsheet in the location field, and it would be very helpful to have it in Figgy.  We are open to your suggestions about which metadata field would be available and would work for this.

- Yes, we can and @escowles , I believe, has done this.

Can we change the rights statement for all items to “Copyright not Evaluated” from the current “No Known Copyright.”

- Yes we can

 We had hoped that we could seamlessly scroll through all of the images associated with a component rather than having to click on each individual image, but we realized that this structure might be necessary in order to display the metadata associated with each image—so that is fine if so.

 We would like to move forward with a DPUL exhibition for this collection, but it might make sense to first work on the Historical Postcard Collection exhibit because you have gotten us started with that and it may be less complicated than the photograph collection.

**Comment by kelea99** [comment]
Spreadsheet for grounds and buildings: https://docs.google.com/spreadsheets/d/1B5PjqUssciL_mq8QuBWJSouGi71AzCQGxEH3A8Hk0fw/edit#gid=640016204

**Comment by cwulfman** [comment]
On 09/07/2020, we (re)ingested pudl0038 (AC111) as a collection of multi-volume works based on component id. On 9/14/2020, @kelea99 wrote to Lynn, Alexis, and Ann Marie, telling them of the ingest of the MVWs and asking for their review.

In an email dated December 18, 2020 (subject RE: Grounds and Buildings MVWs and Historic Postcards DPUL test site ready for review), Lynn Durgin responded to @kelea99 's request for an update with the statement @kelea99 quotes above. In particular, she says

>We had hoped that we could seamlessly scroll through all of the images associated with a component rather than having to click on each individual image, but we realized that this structure might be necessary in order to display the metadata associated with each image—so that is fine if so.

This sounds like they would like to abandon the MVW approach and ingest these as single items.  Is that correct, @kelea99 and @escowles ?

**Comment by escowles** [comment]
Decision 01/19/21: While the stakeholders would like a more seamless experience, they are find with the MVW approach since it allows retaining the metadata for each individual photo.

**Comment by cwulfman** [comment]
@cwulfman : create new collection (linked to AC111) and write script to go through all the source_metadata_identifiers (the collection ids in the spreadsheet) and add them to that collection : https://figgy.princeton.edu/catalog/bd9b272c-fdf6-41a8-baa9-cb4524c777d8

**Comment by cwulfman** [comment]
Can we close this one, @kelea99?

**Comment by kelea99** [comment]
They are still working on the items in DPUL, but I believe our work on this in figgy is complete. Closing ticket.
