### ISSUE TITLE
pudl0083 Versailles: La Grande Galerie de Versailles

### ISSUE THREAD

**Issue by cwulfman** [pulibrary/pudl-migration#54]

**Comment by cwulfman** [comment]
Already migrated; see pulibrary/figgy#3962.

Now we need to

update the PUDL page
create DPUL exhibit?

**Comment by kelea99** [comment]
Question for Julie:
1. are these separated prints part of larger print collection or were they shot from the volume in SC?  If part of a separated prints collection, should items  be linked back to that collection in at 772 field OR should the 772 field contain information for the parent volume (not digitized).

**Comment by kelea99** [comment]
@kelea99 will add these to figgy. each item has its own MARC record.

**Comment by kelea99** [comment]
All images are in PUDL0083 on isilon, 2012 subdirectory AND  2013. plate collections include both: Versailles: La grotte de Versailles and Versailles: La Grande Galerie de Versailles

**Comment by cwulfman** [comment]
Working on pudl0083/2013:

- [x] 00210 = https://catalog.princeton.edu/catalog/10653468
- [x] 00211 = https://catalog.princeton.edu/catalog/10644986
- [x] 00212 = https://catalog.princeton.edu/catalog/10652807

**Comment by kelea99** [comment]
There are three sub-directories- each with two plates on one page. Because there are separate MARC records for each plate, @cwulfman and @kelea99 have decided to include the image of the full page + the image of the individual plate for each item: 

- 2012/00018-19
- [ ] 00018: https://catalog.princeton.edu/catalog/10652257 
- [ ] 00019:  https://catalog.princeton.edu/catalog/10650164 

- 2012/00020-21
- [ ] 00020: https://catalog.princeton.edu/catalog/10655630
- [ ] 00021: https://catalog.princeton.edu/catalog/10654654

- 2012/00022-23
- [ ] 00022: https://catalog.princeton.edu/catalog/10662271
- [ ] 00023: https://catalog.princeton.edu/catalog/10658030

**Comment by cwulfman** [comment]
2012/00018 - 00023 have been ingested into Figgy.

**Comment by kelea99** [comment]
Awesome! reviewed and completed in figgy. all items now available in online catalog.
